src/Entity/PersonaCliente.php
<?php

namespace App\Entity;

use App\Repository\PersonaClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;

/**
 * @ORM\Entity(repositoryClass=PersonaClienteRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class PersonaCliente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=DatosPersona::class, inversedBy="personaCliente", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $datos;

    /**
     * @ORM\OneToOne(targetEntity=UsuarioCliente::class, inversedBy="personaCliente", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $usuario;
    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $tokenRegistro;
    
    /**
     * Set tokenRegistro
     *
     * @param \String $tokenRegistro
     * @ORM\PrePersist
     * @return PersonaCliente
     */
    public function setTokenRegistro()
    {
        if(!$this->tokenRegistro){
            $permitted_chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
            $this->tokenRegistro = substr(str_shuffle($permitted_chars), 0, 8);
        }
        return $this;
    }

    public function __toString(): ?string
    {
        $data= $this->getDatos()->getNombre()." - ";
        
        return $data;
    }

    public function getCliente(): ?string
    {
        $data= $this->getDatos()->getCliente();
        return $data;
    }

    public function __construct()
    {
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getDatos(): ?DatosPersona
    {
        return $this->datos;
    }
    public function getNombre(): ?string
    {
        return $this->datos->getNombre();
    }

    public function setDatos(DatosPersona $datos): self
    {
        $this->datos = $datos;

        return $this;
    }


    public function getUsuario(): ?UsuarioCliente
    {
        return $this->usuario;
    }

    public function setUsuario(UsuarioCliente $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }


    public function getTokenRegistro(): ?string
    {
        return $this->tokenRegistro;
    }

}

src/Entity/PersonaEmpleado.php
<?php

namespace App\Entity;

//use App\Repository\PersonaEmpleadoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonaEmpleadoRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class PersonaEmpleado
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $salario;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fechaCreacion;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fechaUpdate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $lastSesion;

    /**
     * @ORM\Column(type="integer")
     */
    private $activacion;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="string", length=35, nullable=true)
     */
    private $isss;

    /**
     * @ORM\Column(type="string", length=35, nullable=true)
     */
    private $afp;

    /**
     * @ORM\OneToOne(targetEntity=DatosPersona::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $datos;

    /**
     * @ORM\OneToOne(targetEntity=UsuarioEmpleado::class, mappedBy="empleado")
     */
    private $usuariosEmpleado;
    

    /**
     * Set fechaUpdate
     *
     * @param \DateTime $fechaUpdate
     * @ORM\PreUpdate
     * @return UsuarioCliente
     */
    public function setFechaUpdate()
    {
        if(!$this->fechaUpdate){
            $this->fechaUpdate = new \DateTime();
        }
        return $this;
    }

    /**
     * Set fechaCreacion
     *
     * @param \DateTime $fechaCreacion
     * @ORM\PrePersist
     * @return UsuarioCliente
     */
    public function setFechaCreacion()
    {
        if(!$this->fechaCreacion){
            $this->fechaCreacion = new \DateTime();
        }
        return $this;
    }

    public function __toString(): ?string
    {
        return $this->getDatos()->getNombre()."-".$this->getDatos()->getApellido();
    }
  

    public function __construct()
    {
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSalario(): ?float
    {
        return $this->salario;
    }

    public function setSalario(?float $salario): self
    {
        $this->salario = $salario;

        return $this;
    }
    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fechaCreacion;
    }

    public function getFechaUpdate(): ?\DateTimeInterface
    {
        return $this->fechaUpdate;
    }


    public function getLastSesion(): ?\DateTimeInterface
    {
        return $this->lastSesion;
    }

    public function setLastSesion(?\DateTimeInterface $lastSesion): self
    {
        $this->lastSesion = $lastSesion;

        return $this;
    }

    public function getActivacion(): ?int
    {
        return $this->activacion;
    }

    public function setActivacion(int $activacion): self
    {
        $this->activacion = $activacion;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getIsss(): ?string
    {
        return $this->isss;
    }

    public function setIsss(?string $isss): self
    {
        $this->isss = $isss;

        return $this;
    }

    public function getAfp(): ?string
    {
        return $this->afp;
    }

    public function setAfp(?string $afp): self
    {
        $this->afp = $afp;

        return $this;
    }

    public function getDatos(): ?DatosPersona
    {
        return $this->datos;
    }

    public function setDatos(DatosPersona $datos): self
    {
        $this->datos = $datos;

        return $this;
    }

   
    public function getUsuarioEmpleado(): ?UsuarioEmpleado
    {
        return $this->usuariosEmpleado;
    }
    public function setUsuarioEmpleado(UsuarioEmpleado $usuarioEmp): self
    {
        $this->usuariosEmpleado= $usuarioEmp;
        return $this;
    }
    

    public function getUsuariosStr(): ?string
    {
        if($this->getUsuarioEmpleado()!=null)
        return $this->getUsuarioEmpleado()->getUsername();
        else return '';
    }
    

}

src/Form/formulariosantiguos/PersonaEmpleadoType.php
<?php

namespace App\Form;

use App\Entity\PersonaEmpleado;
use App\Entity\TipoEmpleado;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonaEmpleadoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('salario', NumberType::class, array('required' => false, 'attr'=>array('class'=>"form-control", 'pattern' => '\d{4}.\d{2}') ))
            ->add('isss', TextType::class, array('required'=>false, 'attr'=>array('class'=>"form-control", 'placeholder'=>"Escriba su numero de ISSS")))
            ->add('afp', TextType::class, array('required'=>false, 'attr'=>array('class'=>"form-control", 'placeholder'=>"Escriba su numero de AFP")))
            ->add('datos',  DatosPersonaType::class )
        ;
        $builder->get('datos')->remove('giro');
        $builder->get('datos')->remove('ncr');
    }
    

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => PersonaEmpleado::class,
            

        ]);
    }
}
 

src/Controller/PersonaEmpleadoController.php
<?php

namespace App\Controller;

use App\Entity\PersonaEmpleado;
use App\Entity\TipoEmpleado;
use App\Entity\UsuarioEmpleado;
use App\Form\PersonaEmpleadoType;
use App\Form\UsuarioEmpleadoType;
use App\Repository\AgendaRevisionRepository;
use App\Repository\ComentariosRepository;
use App\Repository\PersonaEmpleadoRepository;
use App\Repository\TipoEmpleadoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/personaEmpleado")
 */
class PersonaEmpleadoController extends AbstractController
{
    /**
     * @Route("/", name="persona_empleado_index", methods={"GET"})
     */
    public function index(PersonaEmpleadoRepository $personaEmpleadoRepository): Response
    {
        return $this->render('persona_empleado/index.html.twig', [
            'persona_empleados' => $personaEmpleadoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="persona_empleado_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $personaEmpleado = new PersonaEmpleado();
        $form = $this->createForm(PersonaEmpleadoType::class, $personaEmpleado);
        $mensaje=['0'=> '', '1'=>''];
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $personaEmpleado->setActivacion(0);
            
            $entityManager->persist($personaEmpleado);
            $entityManager->flush();

            return $this->redirectToRoute('persona_empleado_index');
        }
        foreach ($form->getErrors() as $error) {
            $mensaje['0']= $mensaje['0']." ".$error->getMessage();  
        }

        return $this->render('persona_empleado/new.html.twig', [
            'persona_empleado' => $personaEmpleado,
            'form' => $form->createView(),
            'mensajes'=>$mensaje,
        ]);
    }

    /**
     * @Route("/{id}", name="persona_empleado_show", methods={"GET"})
     */
    public function show(Request $request, PersonaEmpleado $personaEmpleado, ComentariosRepository $comen, AgendaRevisionRepository $agendasRepo): Response
    {
        $comentariosEnSeguimiento = $comen->ComentariosPrincipalesPerfilOrdenesMovimientos( $personaEmpleado->getUsuarioEmpleado()->getId());
        
        $cuentaPersonal= false;
        if($this->getUser()->getId() == $personaEmpleado->getUsuarioEmpleado()->getId()){
            $cuentaPersonal=true;
        }
       
        return $this->render('persona_empleado/show.html.twig', [
            'persona_empleado' => $personaEmpleado,
            'banderaCuentaPropia'=> $cuentaPersonal, 
            'comentarios' => $comentariosEnSeguimiento,
            'agendas'=> $agendasRepo->tareasEmpleadoPendientesYnoResueltas( $personaEmpleado->getUsuarioEmpleado()->getId(),)
        ]);
    }

    /**
     * @Route("/{id}/edit", name="persona_empleado_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, PersonaEmpleado $personaEmpleado): Response
    {
        $form = $this->createForm(PersonaEmpleadoType::class, $personaEmpleado);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('persona_empleado_index');
        }

        return $this->render('persona_empleado/edit.html.twig', [
            'persona_empleado' => $personaEmpleado,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}/edit/addUser", name="persona_empleado_edit_add_user", methods={"GET","POST"})
     */
    public function editAddUser(Request $request, PersonaEmpleado $personaEmpleado, TipoEmpleadoRepository $tipoEmpleadoRepo): Response
    {
        $usuario= new UsuarioEmpleado();
        $bandera=['0'=> ''];
        $personaEmpleado->setUsuarioEmpleado($usuario);
        $form = $this->createForm(UsuarioEmpleadoType::class, $usuario);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            //dump($request->request->all()); die;  //descomenta esta linea para que puedas ver como es la forma de tu request
            $dat= $request->request->all()['usuario_empleado']['rolesEmpleado']; //Esto me saca el listado de ids seleccionados de mi lista
            foreach($dat as $idRol){
                $rol= $tipoEmpleadoRepo->findOneBy(array('id'=> $idRol)); //obtengo los objetos correspondientes a esos ids 
                $usuario->addRolesEmpleado($rol); // utilizo el metodo add para ir enlazando los IDS
            }
            if( strlen(  $usuario->getUsuario() )<6 || strlen($usuario->getPassword())<6  ){
                $bandera=['0'=> 'Necesita almenos 6 caracteres en el usuario y la contraseña'];
            }else{
                $usuario->setPassword( password_hash( $usuario->getPassword(), PASSWORD_DEFAULT ));
            }
            if( $bandera['0']=="" ){
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($usuario);
                $entityManager->flush();
                $parametros= $request->request->all();
                $bitacora->setNueva(json_encode (array('data'=>'estos datos no se guardan aca') ), $request->get('_route'), $this->getUser()->getId(), 'Ingreso de nuevo usuario');
                //$bitacora->setParametros(  );
                $entityManager->persist($bitacora);
                $entityManager->flush();
               // dump( $parametros );
               // die;
                return $this->redirectToRoute('persona_empleado_index');
            }
          
        }

        return $this->render('persona_empleado/addUser.html.twig', [
            'persona_empleado' => $personaEmpleado,
            'form' => $form->createView(),
            'bandera'=> $bandera,
        ]);
    }

 
}

templates/vistas/persona_empleado/_delete_form.html.twig
<form method="post" action="{{ path('persona_empleado_delete', {'id': persona_empleado.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ persona_empleado.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vistas/persona_empleado/addUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nueva cuenta empleado{% endblock %}

{% block body %}



    <div class="card shadow-lg border-0 rounded-lg mt-1">
        <div class="card-header justify-content-center"><h3 class="font-weight-light my-4">Crear cuenta de empleado</h3></div>
            <div class="card-body">
                {% if bandera['0']!="" %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ bandera[0] }}</strong>  
                    </div>
                {% endif %}
        
                {{ form_start(form) }}

                    <!-- Form Group (create account submit)-->
                    <div class="form-row">
                        <div class="col-md-4">
                            <label class="small mb-1" >Password</label>
                            {{ form_widget(form.password) }}                                 
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1" >Usuario</label>
                            {{ form_widget(form.usuario) }}    
                        </div>
                        <div class="col-md-4">
                            <label class="small mb-1" >Roles</label>
                            {{ form_widget(form.rolesEmpleado) }} 
                        </div>
                    </div>
                    <br>
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-primary btn-block"> {{ button_label|default('Guardar') }} </button> 
                    </div>
                    
                {{ form_end(form) }}
            
            <div class="card-footer text-center">
        </div>
    </div>


{% endblock %}

{% block js_general %}
    <script src="{{ asset('js/general.js') }}" ></script>
{% endblock %}

templates/vistas/persona_empleado/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PersonaEmpleado{% endblock %}

{% block body %}
    <h1>Edit PersonaEmpleado</h1>

    {{ include('persona_empleado/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('persona_empleado_index') }}">back to list</a>
{% endblock %}

templates/vistas/persona_empleado/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Empleados{% endblock %}

{% block body %}
<a href="{{ path('persona_empleado_new') }}">Nuevo empleado</a>
<div>
    Visibles: 
    <a class="toggle-vis" data-column="0">Correlativo</a> -

</div>
<div> este es solo un div </div>

    <table class="table" id="tabla_empleados">
        <thead>
            <tr>
                <th>Correlativo</th>
                <th>Salario</th>
                <th>Nombre</th>
                <th>Apellido</th>

                <th>Correo1</th>
                <th>Fecha de creacion</th>
                <th>Usuario de sistema</th>
                <th>FechaUpdate</th>

                <th>Última sesión en el sistema</th>
                <th>Activacion</th>
                <th>Color</th>
                <th>ISS</th>

                <th>AFP</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for persona_empleado in persona_empleados %}
            <tr>
                <td>{{ persona_empleado.id }}</td>
                <td>{{ persona_empleado.salario }}</td>
                <td>{{ persona_empleado.datos.nombre }}</td>
                <td>{{ persona_empleado.datos.apellido }}</td>

                <td>{{ persona_empleado.datos.correo1 }}</td>
                <td>{{ persona_empleado.fechaCreacion ? persona_empleado.fechaCreacion|date('Y-m-d') : '' }}</td>
                <td>{{ persona_empleado.usuariosStr }}</td>
                <td>{{ persona_empleado.fechaUpdate ? persona_empleado.fechaUpdate|date('Y-m-d') : '' }}</td>

                <td>{{ persona_empleado.lastSesion ? persona_empleado.lastSesion|date('Y-m-d') : '' }}</td>
                <td>{{ persona_empleado.activacion }}</td>
                <td>{{ persona_empleado.color }}</td>
                <td>{{ persona_empleado.isss }}</td>

                <td>{{ persona_empleado.afp }}</td>
                <td>
                  
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

 
{% endblock %}

{% block js_general %}
    <script src="{{ asset('js/general.js') }}" ></script>
{% endblock %}

templates/vistas/persona_empleado/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}CrearPersonaEmpleado{% endblock %}

{% block body %}

<div class="col-md-12">
    <!-- Basic registration form-->
    <div class="card shadow-lg border-0 rounded-lg mt-1">
        <div class="card-header justify-content-center"><h3 class="font-weight-light my-4">Create Account</h3></div>
        <div class="card-body">
    
        {% if mensajes['0']!="" %}
            <div class="alert alert-danger" role="alert">
                <strong>{{ mensajes[0] }}</strong>
            </div>
        {% endif %}
        {% if mensajes['1'] !="" %}
            <div class="alert alert-success" role="alert">
                <strong>{{ mensajes[1] }}</strong>  : 
                <a href="{{ path('cheque_edit', {'cheque': cheque.id}) }}" id="editarCheque">Editar</a> /
                <a href="{{ path('cheque_new') }}" id="nuevoCheque">Nuevo cheque</a>
            </div>
        {% endif %}
        
            {{ form_start(form) }}
                      
                <div class="form-row">
                    <div class="col-md-3">
                        <!-- Form Group (first name)-->
                        <div class="form-group">
                            <label class="small mb-1" for="inputFirstName">Nombres</label>
                            {{ form_widget(form.datos.nombre) }}
                            {{ form_errors(form.datos.nombre) }}     
                        </div>
                    </div>
                    <div class="col-md-3">
                        <!-- Form Group (last name)-->
                        <div class="form-group">
                            <label class="small mb-1" for="inputLastName">Apellidos</label>
                            {{ form_widget(form.datos.apellido) }}
                            {{ form_errors(form.datos.apellido) }}  
                        </div>
                    </div>
                    <div class="col-md-3">
                        <!-- Form Group (first name)-->
                        <div class="form-group">
                            <label class="small mb-1" >NIT</label>
                            {{ form_widget(form.datos.nit) }}
                            {{ form_errors(form.datos.nit) }}    
                        </div>
                    </div>
                    <div class="col-md-3">
                        <!-- Form Group (last name)-->
                        <div class="form-group">
                            <label class="small mb-1" >DUI</label>
                            {{ form_widget(form.datos.dui) }}
                            {{ form_errors(form.datos.dui) }}    
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6">
                        <label class="small mb-1" for="inputEmailAddress">Email</label>
                        {{ form_widget(form.datos.correo1) }}
                        {{ form_errors(form.datos.correo1) }}    
                    </div>
                    <div class="col-md-6">
                        <label class="small mb-1" for="inputFirstName">Email 2</label>
                            {{ form_widget(form.datos.correo2) }}
                            {{ form_errors(form.datos.correo2) }}    
                    </div>
             
                </div>
                    <div class="form-row">
                        <div class="col-md-3">
                            <!-- Form Group (first name)-->                                
                            <label class="small mb-1" >Documentos1</label>
                            {{ form_widget(form.datos.file) }}
                            {{ form_errors(form.datos.file) }}                                 
                        </div>
                        <div class="col-md-3">
                            <!-- Form Group (first name)-->                                
                            <label class="small mb-1" >Documentos2</label>
                            {{ form_widget(form.datos.file1) }}
                            {{ form_errors(form.datos.file1) }}                                 
                        </div>
                        <div class="col-md-3">
                            <!-- Form Group (first name)-->                                
                            <label class="small mb-1" >Documentos3</label>
                            {{ form_widget(form.datos.file2) }}
                            {{ form_errors(form.datos.file2) }}                                 
                        </div>
                        <div class="col-md-3">
                            <label class="small mb-1" >Departamento</label>
                            {{ form_widget(form.datos.departamento) }}
                            {{ form_errors(form.datos.departamento) }}  
                        </div>
                                           
                        <div class="col-md-6">
                        <!-- Form Group (last name)-->                                
                            <label class="small mb-1" for="inputLastName">Direccion</label>
                            {{ form_widget(form.datos.direccion) }}
                            {{ form_errors(form.datos.direccion) }}    
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-3">
                            <!-- Form Group (first name)-->
                            <div class="form-group">
                                <label class="small mb-1" >Telefono</label>
                                {{ form_widget(form.datos.telefono) }}
                                {{ form_errors(form.datos.telefono) }}    
                            </div>
                        </div>
                        <div class="col-md-3">
                            <!-- Form Group (last name)-->
                            <div class="form-group">
                                <label class="small mb-1" >Celular</label>
                                {{ form_widget(form.datos.celular) }}
                                {{ form_errors(form.datos.celular) }}    
                            </div>
                        </div>
                        <div class="col-md-3">
                            <!-- Form Group (last name)-->
                            <div class="form-group">
                                <label class="small mb-1" >Registro de IVA</label> 
                                {{ form_widget(form.datos.registroIva) }}
                                {{ form_errors(form.datos.registroIva) }}    
                            </div>
                        </div>
                        <div class="col-md-3">
                            <!-- Form Group (last name)-->
                            <div class="form-group">
                                <label class="small mb-1" >Nombre de IVA</label> 
                                {{ form_widget(form.datos.nombreIva) }}
                                {{ form_errors(form.datos.nombreIva) }}    
                            </div>
                        </div>
                    </div>
                <!-- Form Group (create account submit)-->
                <div class="form-row">
                    <div class="col-md-3">
                        <!-- Form Group (first name)-->                                
                            <label class="small mb-1" >Fecha de Nacimiento</label>
                            {{ form_widget(form.datos.fechaNacimiento) }}
                            {{ form_errors(form.datos.fechaNacimiento) }}                                  
                    </div>
                    <div class="col-md-3">
                        <!-- Form Group (first name)-->
                        <div class="form-group">
                            <label class="small mb-1" >Pasaporte</label>
                            {{ form_widget(form.datos.pasaporte) }} 
                            {{ form_errors(form.datos.pasaporte) }}  
                        </div>
                    </div>
                </div>

                 <div class="form-row">
                    <div class="col-md-3">
                        <!-- Form Group (last name)-->
                        <div class="form-group">
                            <label class="small mb-1" >ISSS</label>
                            {{ form_widget(form.isss) }}
                            {{ form_errors(form.isss) }}      
                        </div>
                    </div>
                    <div class="col-md-3">
                        <!-- Form Group (first name)-->
                        <div class="form-group">
                            <label class="small mb-1" >AFP</label>
                            {{ form_widget(form.afp) }}
                            {{ form_errors(form.afp) }}    

                        </div>
                    </div>

                </div>
                <div class="for-row"> 
                    <div class="col-md-3">
                        <div class="form-group">
                        <label class="small mb-1" > PASSWORD </label>
                        ---
                        </div>  
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                        <label class="small mb-1">SALARIO</label>
                        {{ form_widget(form.salario)}} 
                        {{ form_errors(form.salario) }}    
                        </div>
                    </div> 
                    
                </div>

                
                <button type="submit" class="btn btn-primary btn-block"> {{ button_label|default('Guardar') }} </button>
            {{ form_end(form) }}
        </div>

       

        <div class="card-footer text-center">
           
        </div>
    </div>
</div>

 
{% endblock %}
 